POST http://localhost:3333/products
Content-Type: application/json

{
  "name": "dssesisto",
  "description": "sim",
  "price": "60.00",
  "stock": "20"
}

###

GET http://localhost:3333/products


###

PUT  http://localhost:3333/products/91c52da3-3220-4820-8fd7-a5df020ae953
Content-Type: application/json

{
  "name": "Produto 02",
  "description": "arroz da marca tal",
  "price": "35.0",
  "stock": "40"
}

###

DELETE http://localhost:3333/products/91c52da3-3220-4820-8fd7-a5df020ae953