POST http://localhost:3333/products
Content-Type: application/json

{
  "name": "Arroz",
  "description": "Saco de 2kg de Arroz",
  "price": "60.00",
  "stock": "20"
}

###

GET http://localhost:3333/products


###

PUT  http://localhost:3333/products/91c52da3-3220-4820-8fd7-a5df020ae953
Content-Type: application/json

{
  "name": "Arroz Integral",
  "description": "Saco de 2kg de Arroz Integral",
  "price": "70",
  "stock": "15"
}

###

DELETE http://localhost:3333/products/91c52da3-3220-4820-8fd7-a5df020ae953